server.port: 8080
logging:
  level:
    root: INFO
    org.package: INFO

spring:
  application:
    name: test-microservice
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: H2
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: 'jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1'
    username: sa
    password: sa
    driverClassName: org.h2.Driver
